In [45]:
import pandas as pd 
df = pd.read_csv('churn_dataset.csv')
df

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [46]:
df.shape

(10000, 14)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [48]:
df.duplicated().sum()

0

In [49]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [50]:
df = df.drop(['RowNumber','CustomerId','Surname'], axis = 1)
df

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [51]:
df = pd.get_dummies(df, columns=['Geography','Gender'], drop_first=True, dtype=int)
df

CreditScore  Age  Tenure  ...  Geography_Germany  Geography_Spain  Gender_Male
0             619   42       2  ...                  0                0            0
1             608   41       1  ...                  0                1            0
2             502   42       8  ...                  0                0            0
3             699   39       1  ...                  0                0            0
4             850   43       2  ...                  0                1            0
...           ...  ...     ...  ...                ...              ...          ...
9995          771   39       5  ...                  0                0            1
9996          516   35      10  ...                  0                0            1
9997          709   36       7  ...                  0                0            0
9998          772   42       3  ...                  1                0            1
9999          792   28       4  ...                  0                0            0

[10000 rows x 12 columns]

In [52]:
X = df.drop(columns=['Exited'])
y = df['Exited'].values

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [53]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)

In [54]:
X_test_trf

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]])

In [55]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential 
from tensorflow.keras.layers import Dense

In [56]:
model = Sequential()

model.add(Dense(3,activation='sigmoid',input_dim=11))
model.add(Dense(1,activation='sigmoid'))

C:\Users\tanis\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [57]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                 │ (None, 3)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [58]:
model.compile(optimizer='Adam',loss='binary_crossentropy')

In [59]:
model.fit(X_train_trf,y_train,epochs=10)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.7980
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - loss: 0.6037
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5199
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4731
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4583
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4473
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - loss: 0.4315
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4383
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - loss: 0.4272
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4263


In [60]:
model.layers[0].get_weights()

[array([[-0.2757103 , -0.01546981,  0.03538525],
        [ 1.7300948 , -1.3614905 , -1.0016311 ],
        [-0.10816257,  0.28393856,  0.02914178],
        [ 0.1357436 , -0.55817497, -0.05460681],
        [ 0.17867398,  0.80392927,  0.38226816],
        [-0.16398856, -0.04128915, -0.07696049],
        [-0.063151  ,  0.38276696,  1.1575863 ],
        [ 0.05233452, -0.27811828,  0.04044712],
        [ 0.28969973, -0.18787904, -0.9130995 ],
        [ 0.16644405, -0.02904141,  0.07599954],
        [-0.09597545,  0.319581  ,  0.7127297 ]], dtype=float32),
 array([-0.44732857,  0.47609702,  0.8520237 ], dtype=float32)]

In [61]:
model.layers[1].get_weights()

[array([[ 0.93777657],
        [-0.6509703 ],
        [-1.4343207 ]], dtype=float32),
 array([-0.63284385], dtype=float32)]

In [64]:
y_log = model.predict(X_test_trf)
y_log

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


array([[0.25287232],
       [0.35421184],
       [0.17019404],
       ...,
       [0.15366203],
       [0.13859232],
       [0.23396921]], dtype=float32)

In [66]:
import numpy as np
y_pred = np.where(y_log > 0.5, 1,0)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [67]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8135